

%\documentclass{article}
\documentclass[a4paper]{article}
\setlength{\parskip}{0.7ex plus0.1ex minus0.1ex}
\setlength{\parindent}{0em}

% Packages
\usepackage{a4wide}
\usepackage[american]{babel}
\usepackage{floatrow}
\usepackage{url}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{enumitem}
\usepackage{authblk}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}

% References
\usepackage[backend=bibtex, sorting=none]{biblatex}
\bibliography{references}
\usepackage{csquotes}

\begin{filecontents*}{references.bib}
@misc{eUtiles,
    url = {http://www.ncbi.nlm.nih.gov/books/NBK25500/}
}
\end{filecontents*}

%Title
\title{\emph{webQueries}: Retrieve genes or protein annotations by
    querying NCBI.}

% Authors
\author[1]{Frederic Commo}

\affil[1]{INSERM U981, Institut Gustave Roussy, 114 rue Edouard Vaillant,
    94805 Villejuif, France}

\renewcommand\Authands{ and }
\renewcommand\Affilfont{\fontsize{9}{10.8}\itshape}

\begin{document}

\maketitle

%\VignetteIndexEntry{Using webQueries}
%\VignetteEngine{knitr::knitr}

% Chunk setup
<<setup, include=FALSE>>=
require(knitr)
opts_chunk$set(fig.align='center', fig.width=5.5, fig.height=4.5,
    dev='pdf', prompt=TRUE, comment=NA, highlight=FALSE, tidy=FALSE)
@

\section{Introduction}
\texttt{webQueries} provides R functions for retrieving up-to-date gene and
protein annotations from NCBI databases, given HUGO symbols or ids, e.g. 
entrezgene or Uniprot ids.\\
The main function, \texttt{runQuery()}, is a wrapper for the NCBI E-utilities
functions \cite{eUtiles}, and is designed to query \emph{Gene},
\emph{Protein}, and \emph{SNP} databases.
\texttt{runQueries} requires a functional web connexion.\\
In case a HUGO symbol is called, \texttt{runQuery} first interogate NCBI in 
order to get identifiers, using E-utilities \texttt{Esearch}, then use the 
returned values to get the corresponding annotations, using E-utilities
\texttt{Esummary}.

\section{Examples}
Here are some examples showing how a single, or multiple, annotation(s) can be
retrieved using either official symbols or identifiers.\\

Querying the NCBI \emph{Gene} database, using HUGO symbols:

<<gene>>=
require(webQueries)
gquery <- runQuery("erbb2", "gene")

# The first 5 items
as.list(gquery)[1:5]
@

Querying the NCBI \emph{Protein} database, using Uniprot ids:

<<prot>>=
pquery <- runQuery("P04626", "protein", bySymbol = FALSE)

# The first 5 items
as.list(pquery)[1:5]
@

When querying the NCBI \texttt{SNP} database, one may not be interested only in
the last updates, but in all the outputs. To do so, the \texttt{updateOnly}
argument must be set to \texttt{FALSE}:

<<snpQuery>>=
query <- runQuery("erbb2", "snp", updateOnly = FALSE)
query[,1:5]
@

A simple way to run multiple queries would be to call \texttt{runQuery} within
a loop, e.g. \texttt{lapply}. However, each returned xml file may not contain
exactly the same items - some may not be available.
\texttt{multiQueries} takes care of this, and returns the common items over
all the queries.

<<multi>>=
# Multiple queries on the Gene database, using HUGO symbols
ids <- c("egfr", "erbb2", "fgfr1")
annots <- multiQueries(ids, "gene")
annots[,1:8]
# List of returned items
names(annots)
@

\section{Accessing R code}
R source code for \texttt{webQueries} is available on github:
\url{https://github.com/fredcommo/webQueries}

\printbibliography

\end{document}
